# Site settings
author: Nick Oseland
title: Exploratory Data Analysis
header-img: img/home-bg.png
email: noseland84@gmail.com
copyright_name: Nick Oseland
description: > # this means to ignore newlines until "baseurl:"
  EDA
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Oseland84

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
